{% set name = "jupyterlab_search_replace" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower|replace("_", "-") }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0db6af5eb9b8325d18669a7dc21191b67358b72c456eca3719fb576e218f49cc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - jupyterlab =3
    - jupyter-packaging >=0.10,<2.0
  run:
    - python >=3.7,<4.0
    - jupyter_server >=1.0,<2.0
    - ripgrep

test:
  imports:
    - jupyterlab_search_replace
  requires:
    - jupyterlab =3
    - pip
  commands:
    - pip check
    - jupyter server extension list
    - jupyter server extension list 2>&1 | grep -ie "jupyterlab_search_replace.*OK"  # [not win]
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab-search-replace.*OK.*(python, jupyterlab.search.replace)"  # [not win]

about:
  home: https://github.com/jupyterlab-contrib/search-replace
  summary: Search and replace across files
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fcollonval
